# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tfnev_codeepneat_mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_genome_analysis = QtWidgets.QWidget(self.centralwidget)
        self.widget_genome_analysis.setGeometry(QtCore.QRect(60, 10, 930, 660))
        self.widget_genome_analysis.setObjectName("widget_genome_analysis")
        self.ga_vline_1 = QtWidgets.QFrame(self.widget_genome_analysis)
        self.ga_vline_1.setGeometry(QtCore.QRect(450, 0, 20, 660))
        self.ga_vline_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.ga_vline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ga_vline_1.setObjectName("ga_vline_1")
        self.ga_hline_1 = QtWidgets.QFrame(self.widget_genome_analysis)
        self.ga_hline_1.setGeometry(QtCore.QRect(0, 320, 460, 20))
        self.ga_hline_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.ga_hline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ga_hline_1.setObjectName("ga_hline_1")
        self.ga_list_generations = QtWidgets.QListWidget(self.widget_genome_analysis)
        self.ga_list_generations.setGeometry(QtCore.QRect(10, 370, 440, 290))
        self.ga_list_generations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ga_list_generations.setObjectName("ga_list_generations")
        self.ga_lbl_list_heading = QtWidgets.QLabel(self.widget_genome_analysis)
        self.ga_lbl_list_heading.setGeometry(QtCore.QRect(60, 340, 340, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ga_lbl_list_heading.setFont(font)
        self.ga_lbl_list_heading.setObjectName("ga_lbl_list_heading")
        self.ga_widget_genome_visualization = QtWidgets.QWidget(self.widget_genome_analysis)
        self.ga_widget_genome_visualization.setGeometry(QtCore.QRect(470, 0, 460, 460))
        self.ga_widget_genome_visualization.setObjectName("ga_widget_genome_visualization")
        self.ga_lbl_genome_id = QtWidgets.QLabel(self.widget_genome_analysis)
        self.ga_lbl_genome_id.setGeometry(QtCore.QRect(470, 470, 460, 20))
        self.ga_lbl_genome_id.setAlignment(QtCore.Qt.AlignCenter)
        self.ga_lbl_genome_id.setObjectName("ga_lbl_genome_id")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 20))
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.action_documentation = QtWidgets.QAction(MainWindow)
        self.action_documentation.setObjectName("action_documentation")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_help.addAction(self.action_documentation)
        self.menu_file.addAction(self.action_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tensorflow-Neuroevolution Visualizer"))
        self.ga_lbl_list_heading.setText(_translate("MainWindow", "List of generations and their best genome"))
        self.ga_lbl_genome_id.setText(_translate("MainWindow", "Genome ID "))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.action_documentation.setText(_translate("MainWindow", "Documentation"))
        self.action_close.setText(_translate("MainWindow", "Close TFNE Backup"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
