# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tfnev_codeepneat_mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.cw_genome_analysis = QtWidgets.QWidget(MainWindow)
        self.cw_genome_analysis.setEnabled(True)
        self.cw_genome_analysis.setObjectName("cw_genome_analysis")
        self.vline_1 = QtWidgets.QFrame(self.cw_genome_analysis)
        self.vline_1.setGeometry(QtCore.QRect(250, 10, 20, 310))
        self.vline_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline_1.setObjectName("vline_1")
        self.vline_2 = QtWidgets.QFrame(self.cw_genome_analysis)
        self.vline_2.setGeometry(QtCore.QRect(450, 10, 20, 660))
        self.vline_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline_2.setObjectName("vline_2")
        self.list_generations = QtWidgets.QListWidget(self.cw_genome_analysis)
        self.list_generations.setGeometry(QtCore.QRect(70, 10, 180, 300))
        self.list_generations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_generations.setObjectName("list_generations")
        self.list_genomes = QtWidgets.QListWidget(self.cw_genome_analysis)
        self.list_genomes.setGeometry(QtCore.QRect(270, 10, 180, 300))
        self.list_genomes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_genomes.setObjectName("list_genomes")
        self.hline_1 = QtWidgets.QFrame(self.cw_genome_analysis)
        self.hline_1.setGeometry(QtCore.QRect(60, 310, 400, 20))
        self.hline_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline_1.setObjectName("hline_1")
        self.hline_2 = QtWidgets.QFrame(self.cw_genome_analysis)
        self.hline_2.setGeometry(QtCore.QRect(460, 410, 530, 20))
        self.hline_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline_2.setObjectName("hline_2")
        self.lbl_generation_info = QtWidgets.QLabel(self.cw_genome_analysis)
        self.lbl_generation_info.setGeometry(QtCore.QRect(70, 330, 380, 20))
        self.lbl_generation_info.setObjectName("lbl_generation_info")
        self.lbl_genome_info = QtWidgets.QLabel(self.cw_genome_analysis)
        self.lbl_genome_info.setGeometry(QtCore.QRect(470, 430, 530, 20))
        self.lbl_genome_info.setObjectName("lbl_genome_info")
        MainWindow.setCentralWidget(self.cw_genome_analysis)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 20))
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.action_documentation = QtWidgets.QAction(MainWindow)
        self.action_documentation.setObjectName("action_documentation")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_help.addAction(self.action_documentation)
        self.menu_file.addAction(self.action_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tensorflow-Neuroevolution Visualizer"))
        self.lbl_generation_info.setText(_translate("MainWindow", "<generation information displayed here>"))
        self.lbl_genome_info.setText(_translate("MainWindow", "<genome information displayed here>"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.action_documentation.setText(_translate("MainWindow", "Documentation"))
        self.action_close.setText(_translate("MainWindow", "Close TFNE Backup"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
