# Import functions
from tfne.deserialization.deserialization import load_genome
from tfne.deserialization.deserialization import load_population
from tfne.deserialization.deserialization import load_population_from_state
